baseurl = "https://blog.coredns.io/"
languageCode = "en-us"
title = "CoreDNS News"
copyright = "CoreDNS All Rights Reserved"
theme = "hugo-zen"

[params]
  logo      = "/images/cloud.jpg"
  twitter   = "https://twitter.com/corednsio"
#  facebook  = "https://www.facebook.com/ochiishikoichiro"
  github    = "https://github.com/coredns/coredns"
  email     = "miek@miek.nl"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[params.authors.miek]
  name = "Miek Gieben"
  location = "London, UK"
  email = "miek@miek.nl"
  twitter = "https://twitter.com/miekg"
  github = "https://github.com/miekg"

[params.authors.john]
  name = "John Belamaric"
  location = "Washington, DC"
  email = "jbelamaric@infoblox.com"
  twitter = "https://twitter.com/johnbelamaric"
  github = "https://github.com/johnbelamaric"
